### ISSUE TITLE
Update ci/build-package-docs.sh to generate resource docs

### ISSUE THREAD

**Issue by justinvp** [pulumi/scripts#104]
https://github.com/pulumi/docs/blob/master/scripts/gen_resource_docs.sh needs to be updated to be able to specify a single package (similar to how `PKGS` can be set before calling `run_typedoc.sh`) and then `ci/build-package-docs.sh` needs to be updated to call `gen_resource_docs.sh`.

**Comment by chrsmith** [comment]
In https://github.com/pulumi/docs/pull/2820, Praneet mentioned the following:

> I also updated the gen_resource_docs.sh script to accept a provider name override to generate docs for a single provider, which is required for CI scenarios when we release a new provider. [This commit](https://github.com/pulumi/docs/pull/2820/commits/24037853eebd8518e5f3dde626b2a257a94f4251) has those changes. We are not yet ready to make the upstream script changes to make use of this (though I expect it to work). My main motivation for doing this is for my local development reasons.

So 🤞 everything will "just work" if we use those parameters. Will try and confirm...

**Comment by praneetloke** [comment]
@chrsmith I thought I'd let you know that I just merged a PR in the docs repo that adds two additional optional parameters for use in CI. Please see https://github.com/pulumi/docs/blob/master/scripts/gen_resource_docs.sh#L11. So for example, for AWS one can pass `./scripts/gen_resource_docs.sh aws true v2.0.0` where v2.0.0 is the version of the resource plugin to be installed by the script. If there is no need to override the version, then simply calling `./scripts/gen_resource_docs.sh aws true` is enough and the script will do its best to install the latest _released_ version. But in CI, I think we can always pass the version to that script because we will run that script in the context of making a new release to a provider.

One more important thing, because there is more than one person working on docs right now, I have committed a local override of `pulumi/pulumi` to the `go.mod` file for the resource docs driver tool [`resourcedocsgen`](https://github.com/pulumi/docs/blob/master/tools/resourcedocsgen/go.mod). I am guessing that in CI we won't have `pulumi/pulumi` cloned in the environment locally in the context of a provider repo. So perhaps we will need to get rid of the local override from the go.mod file to enable the CI scenario.

Hope I didn't confuse you with all of that, but please do let me know if you need any additional clarification.
